### ISSUE TITLE
FIRST device approval

### ISSUE THREAD

**Issue by jzhu98** [HuskieRobotics/roborioExpansion#27]
I've summarized the proposal requirements from the recent [blog post](http://www.usfirst.org/roboticsprograms/frc/blog-myrio-expansion-port-its-back) about the MXP approval rules. They are the same as [last year's](http://www.usfirst.org/roboticsprograms/frc/blog-myRIO-Expansion-Port-Whats-the-Deal).

**Deadline**: November 27, 2015, sent to frcparts@usfirst.org
- Device legality is confidential until FIRST discloses it publicly (by Kickoff, at the latest)
- Feedback and decision within one week of receipt
- [ ] PWM pins are a direct pass-through
- [ ] PWM pins breakouts are visibly obvious
- [ ] Proposals must include:
  - [ ] 5 device samples
  - [ ] Description of inventory and distribution for commercial availability to FRC community
  - [ ] A sponsoring **Vendor** (FIRST 2015 definition)
  - [ ] Documentation (user guide, specs, etc.) + other resources (websites, videos, etc.)
  - [ ] Pricing

Descriptions / documentation may be sent ahead of the samples.

FIRST recommends, but does not require that the device accommodate a pass-through for any unused pins.

**Comment by wiresboy** [comment]
Yeah, that is pretty much what we expected. The important information is the deadline, November 27th! We have 1 month, 5 days to get this finished. Let's do this!
