### ISSUE TITLE
LCD Backlight Labview control

### ISSUE THREAD

**Issue by wiresboy** [HuskieRobotics/roborioExpansion#39]
Assuming a Parallax LCD, how are we going to control this?

I would suggest that the LCD input have a 3-option input. 

1. (default). Leave LCD in current state, don't include that byte.
2. Turn LCD on. Labview code inserts the `LCD on` character to beginning of byte stream.
3. Turn LCD off. Labview code inserts the `LCD off` character to beginning of byte stream.

**Comment by gcschmit** [comment]
I created an LCD Backlight typedef and updated the HB_DisplayLCD VI to use it as specified in this issue.

Commit: 1536f107b0fc8a744bdaaa9fc7c6a35fc4a61a2f
