### ISSUE TITLE
Update HB_ConfigureDIO VI to check for invalid pins

### ISSUE THREAD

**Issue by gcschmit** [HuskieRobotics/roborioExpansion#61]
Check issue #46 for the details.

**Comment by Hobbs2000** [comment]
I updated the HB_ConfigureDIO VI, but I would like someone else to take a look at it before this issue gets closed

**Comment by gcschmit** [comment]
I'll take a look tomorrow.

**Comment by wiresboy** [comment]
I modified his work slightly. Please also check HB_ConfigureLED.vi.

Why are the DIO and LED strip typedefs different? Disabling a value doesn't seem to do anything when that typedef is used as a control.

**Comment by gcschmit** [comment]
Both VIs look good to me.

The typedefs are different because of the disabled values. I made a mistake and created these as controls instead of typedef; so, the disabled values were still selectable. I've fixed that now.
