### ISSUE TITLE
Create ReadDIO poly VI to read a single DIO line?

### ISSUE THREAD

**Issue by gcschmit** [HuskieRobotics/roborioExpansion#62]
Should we create a ReadDIO polymorphic VI similar to the ReadAI polymorphic VI that makes it easy to read a single DIO channel?

**Comment by wiresboy** [comment]
Yes. It shouldn't affect the API or HB code at all, correct?

**Comment by gcschmit** [comment]
Correct.

**Comment by gcschmit** [comment]
To clarify, this affects the LV API but in a backward compatible manner.

**Comment by gcschmit** [comment]
Thinking about this a bit more, I propose that we rename the current VI to HB_ReadDIOAllChannels before this initial release. This makes it easier in the future to create a HB_ReadDIO polyVI along with a HB_ReadDIOSingleChannel VI.

Thoughts?

**Comment by wiresboy** [comment]
Sounds good to me.

**Comment by gcschmit** [comment]
Changed the VI name as proposed.
