### ISSUE TITLE
Create HB_GetFirmwareVersion.vi

### ISSUE THREAD

**Issue by gcschmit** [HuskieRobotics/roborioExpansion#64]
Put this in the Utils sub palette.

**Comment by wiresboy** [comment]
Calvin did the majority of this one, I just made a couple small fixes. It still needs the correct icon, and needs to go into the Utils palette, which I will let @gcschmit do. I just tested its functionality, and it is working great!

**Comment by gcschmit** [comment]
Moved to the sub palette.
